#
# Retrieve interface details
#
---
- name: "Fetch interfaces"
  ntc_show_command:
    command: "show interface"
    template_dir: "{{ inventory_dir }}/lib/ntc-ansible/ntc-templates/templates"
    platform: "{{ platforms[os] }}"
    host: "{{ inventory_hostname }}"
    username: "{{ ansible_ssh_user }}"
    password: "{{ ansible_ssh_pass }}"
    connection_args:
      ssh_config_file: "{{ inventory_dir }}/ssh_config"
  register: interfaces
  tags: ['fetch', 'fetch-interfaces']

- debug:
    msg: "{{ interfaces }}"
  tags: ['fetch', 'fetch-interfaces']

- copy:
    content: "{{ interfaces.response|to_nice_yaml(indent=2) }}"
    dest: "{{ host_results }}/interfaces-{{mcast_group}}.yaml"
  tags: ['fetch', 'fetch-interfaces']

# vim: set ts=2 shiftwidth=2 expandtab:
